services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
      - /app/public/profileImages
    networks:
      - chat-network

  db:
    image: postgis/postgis:15-3.5-alpine
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - chat-network
  websocket:
    build: .
    command: node websocket-server.js
    ports:
      - "4001:4000"
    networks:
      - chat-network

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge
